services:
  discord_bot:
    platform: linux/amd64
    build:
      context: ./
      dockerfile: Dockerfile
    image: aida0/gitfolio_discord_bot:latest
    container_name: discord_bot
    ports:
      - target: 8000
        published: 81
        protocol: tcp
      - target: 8000
        published: 444
        protocol: tcp
      - target: 8000
        published: 8000
        protocol: tcp
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
      