apiVersion: v1
kind: Service
metadata:
  name: discord
spec:
  ports:
    - port: 8000
      targetPort: 8000
      name: fastapi
    - port: 80
      targetPort: 80
      name: http
    - port: 443
      targetPort: 443
      name: https
  selector:
    app: discord