apiVersion: v1
kind: Service
metadata:
  name: discord
spec:
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
    - port: 80
      targetPort: 80
      protocol: TCP
    - port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app: discord