apiVersion: v1
kind: Service
metadata:
  name: discord
spec:
  ports:
    - name: fastapi
      port: 8000
      targetPort: 3000
      protocol: TCP
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app: discord