apiVersion: v1
kind: Service
metadata:
  name: discord
spec:
  ports:
    - port: 8000
      targetPort: 8000
    - port: 80
      targetPort: 80
    - port: 443
      targetPort: 443
  selector:
    app: discord