apiVersion: v1
kind: Service
metadata:
  name: discord
spec:
  ports:
    - name: FastAPI
      port: 8000
      targetPort: 8000
      protocol: TCP
    - name: HTTP
      port: 80
      targetPort: 80
      protocol: TCP
    - name: HTTPS
      port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app: discord